// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdtqiycpgzreocydbkkb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkdHFpeWNwZ3pyZW9jeWRia2tiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwMzExOTAsImV4cCI6MjA2NDYwNzE5MH0.tU74Oef_4kS2kSxXa_ESz2jx_ZAEakAHy6H4ZfkX5IU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});